language: python
python:
- '3.7'
git:
  submodules: false
before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_8ebb1ef83f64_key
    -iv $encrypted_8ebb1ef83f64_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - >-
    openssl aes-256-cbc
    -K $encrypted_8ebb1ef83f64_key
    -iv $encrypted_8ebb1ef83f64_iv
    -in github_deploy_key2.enc
    -out github_deploy_key2
    -d
  - chmod 600 github_deploy_key
  - chmod 600 github_deploy_key2
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - ssh-add github_deploy_key2
  - git submodule init
  - git submodule update
install:
- pip install -r requirements.txt
script: make
after_success:
- source push.sh
env:
  matrix:
  - ZB_SEARCH_PREFIX_URI=groups/2504334 ZB_OUT_DIR="data/testRepo" ZB_FILE="${ZB_OUT_DIR}/latest.json"
    ZB_VERSION_FILE="${ZB_OUT_DIR}/.last-modified-version"
  global:
  - PYTHONIOENCODING="utf-8"
  - ZB_PYTHON=python
  - ZB_LOG_LEVEL=INFO
  - ZB_SEARCH_TAG=""