language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: make
after_success:
- source push.sh
env:
  matrix:
  - ZB_SEARCH_PREFIX_URI=groups/2504334 ZB_OUT_DIR="data/testRepo" ZB_BIBTEX_FILE="${ZB_OUT_DIR}/my-bibliography" ZB_VERSION_FILE="${ZB_OUT_DIR}/.last-modified-version"
  global:
  - PYTHONIOENCODING="utf-8"
  - ZB_PYTHON=python
  - ZB_LOG_LEVEL=INFO
  - ZB_SEARCH_TAG=""
  - secure: TlZnnBOR8x8JnC07MvRJYeGsfIyj5d5wVezKWgizw7SnYQfYVaf62iKglTdAUdtldTthsAUhonX57t65/FoM4DnNmYESv1TGjoDSoyH4SWhkMmnP84J89BHbcHiHxnRgqDc4cCqRczElAh+4S105+EfyoOf3mNMmvcXg/zPmdzTaefCxIfbVpMLn7oLW1hVTSYPvnDMk7pzw6wKa2v0tWqYjc+FH62A2OZ/XjFvBjdFpbe9cCyT1jhWZglr5oZACkEz4OQdSRcp/Rplps17Hl6XCtKiwdlyIKdA0ZprtVvnduwxz5hxytsZ1b0qRIuFeoooSnjpNCfQ39l4vRL471OWXk/ggWKS9+0jkzrD6zJhsyq/FlAF/3fhnstXbM8vSnCYIqWluafhXSR78BLXwnHf0fmRJ0sHufjr+pzNuhqUdJV89+StLLLSJdfauxENtAI2Tm2FIemGfiXtkvmgQYaomV1+uqiPtItWxSPNUxarxegY7TywkQM7jh4U1L/KzXLNVWYBy1CyNu8FkrAnvcFpL6uOs8ZVgHxdMgn7fqkyFOhI8EXZC+EhWjo1Sri4D9c8pycGDc6lHOQUYFJa0NsMcYVYyrp6FtlP5Kb0Ioj88jp3SacCIgEP+6K2PQBogapnV43cuuTYEIag/7FWxuUyTzKEZo4Iokkbk69a54KY=
  - secure: m28Mv8G6OCRm+NW690z+/VKW9yScsWGyJ+vLJH4BJnIKCgLPO1ilH0I6P4q+fkpG6Tn/NcrTOdGXvl1jJmSqMddplWrij2l9YyZAB8HbE/EmfstDK2RLynB7laWhWSf0u33u1z9sIxDbE9qC85I1CYNEsf8WxNWiMD8W0Id6q4FD4TK3YE2u/2TIk5jnvwD5F44K5PzAlkSMZkxGAHpwWvlfn0wsQsGN3BA1QNxWCMYaaOMOIjkWdxmN25RroOVqdvsz9x9ArJcXNmJfiRPW+FJKMMPBZOI7YLf6sFKi8sMxYdrRTEkcrnVL6JMcgY1Ep67eluhLGAglkpm6GDnTQ63Zbk1x8gtbXumky5MkuyxAqr+gzt8k4O1HdHkz3V48C2o0QeIo/l9uUmWRrr6ZTvg1nP34NQHBwp4RLCSdCRWC6uEp/EGl+xq36VWLdnu8mOY5/1eHRRN42L3UjFZa9uSK4kkYQzpBQOyiY7exGvRhi0uO6GUtG8W5SpIHAB93ZpxYRfCaYTY0LZRIKGiPp4w13bl3vBk4r4tmiwWzm5rQpLEA/pSOpZTVuIn4s7ohn0aTHtnKLgoAaCzrmdbkDHQJIAQu4w95jqtEcSJ0TqnMnbDaPjgMO/qqeBbq8ZjrsW8HBWoxMvtUABjF/7IYRcEGzx1bkGPn8YkkP+USctM=
  