language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: make
after_success:
- source push.sh
env:
  matrix:
    - ZB_SEARCH_PREFIX_URI=2504334 ZB_OUT_DIR="data/testRepo"
  global:
    secure: TlZnnBOR8x8JnC07MvRJYeGsfIyj5d5wVezKWgizw7SnYQfYVaf62iKglTdAUdtldTthsAUhonX57t65/FoM4DnNmYESv1TGjoDSoyH4SWhkMmnP84J89BHbcHiHxnRgqDc4cCqRczElAh+4S105+EfyoOf3mNMmvcXg/zPmdzTaefCxIfbVpMLn7oLW1hVTSYPvnDMk7pzw6wKa2v0tWqYjc+FH62A2OZ/XjFvBjdFpbe9cCyT1jhWZglr5oZACkEz4OQdSRcp/Rplps17Hl6XCtKiwdlyIKdA0ZprtVvnduwxz5hxytsZ1b0qRIuFeoooSnjpNCfQ39l4vRL471OWXk/ggWKS9+0jkzrD6zJhsyq/FlAF/3fhnstXbM8vSnCYIqWluafhXSR78BLXwnHf0fmRJ0sHufjr+pzNuhqUdJV89+StLLLSJdfauxENtAI2Tm2FIemGfiXtkvmgQYaomV1+uqiPtItWxSPNUxarxegY7TywkQM7jh4U1L/KzXLNVWYBy1CyNu8FkrAnvcFpL6uOs8ZVgHxdMgn7fqkyFOhI8EXZC+EhWjo1Sri4D9c8pycGDc6lHOQUYFJa0NsMcYVYyrp6FtlP5Kb0Ioj88jp3SacCIgEP+6K2PQBogapnV43cuuTYEIag/7FWxuUyTzKEZo4Iokkbk69a54KY=
