language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script: make
after_success:
- source push.sh
env:
  matrix:
  - ZB_SEARCH_PREFIX_URI=groups/2504334 ZB_OUT_DIR="data/testRepo" ZB_FILE="${ZB_OUT_DIR}/latest.json"
    ZB_VERSION_FILE="${ZB_OUT_DIR}/.last-modified-version"
  global:
  - PYTHONIOENCODING="utf-8"
  - ZB_PYTHON=python
  - ZB_LOG_LEVEL=INFO
  - ZB_SEARCH_TAG=""